export const FEATURE_FLAG_KEYS = [
    'ENABLE_MULTI_INDEX_FEDERATION',
    'ENABLE_LAZY_RETRIEVAL',
    'ENABLE_SEMANTIC_SUMMARY',
    'ENABLE_INTENT_ROUTING',
    'ENABLE_SEMANTIC_MEMORY',
    'ENABLE_QUERY_DECOMPOSITION',
    'ENABLE_WEB_RERANKING',
    'ENABLE_SEMANTIC_BOOST',
    'ENABLE_RESPONSE_STORAGE',
    'ENABLE_ADAPTIVE_RETRIEVAL',
    'ENABLE_HYBRID_WEB_RETRIEVAL'
];
//# sourceMappingURL=featureFlags.js.map