name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Verify pnpm installation
        run: pnpm --version
      - name: Install dependencies (workspace)
        run: pnpm -r install --frozen-lockfile=false
      - name: Lint
        run: pnpm -r lint
      - name: Build
        run: pnpm -r build
      - name: Test
        run: pnpm -r --if-present test
